[package]
name = "ixy"
version = "0.1.0"
authors = ["Simon Ellmann <simon.ellmann@tum.de>"]
edition = "2018"

[dependencies]
libc = "0.2"
byteorder = "1"
lazy_static = "1.4.0"
log = "0.4"
# ------------------------
nullnet-firewall = "0.2.0"
etherparse = "0.13.0"
crossterm = "0.27.0"
